# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-21 13:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Charginglog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('timestamp_value', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'charginglog',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'customer',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('destinationposlat', models.FloatField(blank=True, db_column='destinationPosLat', null=True)),
                ('destinationposlon', models.FloatField(blank=True, db_column='destinationPosLon', null=True)),
            ],
            options={
                'db_table': 'delivery',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Drone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('consumption', models.FloatField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=45, null=True)),
                ('radius', models.IntegerField(blank=True, null=True)),
                ('weight', models.IntegerField(blank=True, null=True)),
                ('customer_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='drone.Customer')),
            ],
            options={
                'db_table': 'drone',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Droneposition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('altitude', models.FloatField(blank=True, null=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('timestamp_value', models.DateTimeField(auto_now=True)),
                ('drone_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='drone.Drone')),
            ],
            options={
                'db_table': 'droneposition',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Packet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'packet',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long', models.FloatField(blank=True, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Station',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'stock',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='packet',
            name='stock_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='drone.Stock'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='drone_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='drone.Drone'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='stock_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='drone.Stock'),
        ),
        migrations.AddField(
            model_name='charginglog',
            name='drone_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='drone.Drone'),
        ),
        migrations.AddField(
            model_name='charginglog',
            name='station_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='drone.Station'),
        ),
    ]
