# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-22 22:32
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('drone', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='packet',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='station',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='drone',
            name='status',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'En Repos'), (2, 'En Mission'), (3, 'En Recharge'), (4, 'Detruit'), (5, 'Disparu')], max_length=9, null=True),
        ),
    ]
