# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-22 23:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('drone', '0002_auto_20170523_0032'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='packet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='drone.Packet'),
        ),
        migrations.AlterField(
            model_name='packet',
            name='status',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Au Stock'), (2, 'En Livraison'), (3, 'Pas disponible')], max_length=5, null=True),
        ),
    ]
