# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-22 23:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drone', '0003_auto_20170523_0106'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='anticipated_charged_battery',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='station',
            name='num_charged_battery',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
