# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-23 18:00
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('drone', '0004_auto_20170523_0117'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='status',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'NOT STARTED'), (2, 'STARTED'), (3, 'ABORTED'), (4, 'FINISHED')], max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='drone',
            name='status',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'UNINIT'), (2, 'BOOT'), (3, 'CALIBRATING'), (4, 'STANDBY'), (5, 'ACTIVE'), (6, 'CRITICAL'), (7, 'EMERGENCY'), (8, 'POWEROFF')], max_length=15, null=True),
        ),
    ]
